x-service: &service
  image: sample-project-backend:current
  restart: unless-stopped
  depends_on:
    redis:
      condition: service_started
    rabbitmq:
      condition: service_started
  env_file:
    - path: '/etc/sample-project/.env'
      required: false
  environment:
    SAMPLE_PROJECT_SETTING_CHANNEL_LAYERS: '{"default":{"CONFIG":{"hosts":[["redis", 6379]]}}}'
    SAMPLE_PROJECT_SETTING_CELERY_RESULT_BACKEND: redis://redis:6379/0
    SAMPLE_PROJECT_SETTING_CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672


services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sample_project_prod_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:6.2.6-alpine
    container_name: sample_project_prod_redis
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis-data:/var/lib/redis

  backend:
    <<: *service
    container_name: sample_project_prod_backend
    command: ./run-django.sh
    ports:
      - 127.0.0.1:8000:8000

  celery:
    <<: *service
    command: ./run-celery.sh
    container_name: sample_project_prod_celery
    depends_on:
      - rabbitmq

  celery-beat:
    <<: *service
    container_name: sample_project_prod_celerybeat
    command: ./run-celery-beat.sh
    depends_on:
      - rabbitmq


volumes:
  redis-data:
    driver: local