name: Quality Assurance
on: [pull_request, workflow_call]


jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.12.2-slim-bookworm

    services:
      db:
        image: postgres:16.2-alpine
        env:
          POSTGRES_DB: sample_project
          POSTGRES_USER: sample_project
          POSTGRES_PASSWORD: sample_project

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.3

      - name: Install Dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          SAMPLE_PROJECT_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
          SAMPLE_PROJECT_LOCAL_SETTINGS_PATH: './sample_project/config/settings/templates/settings.github.py'
